# Introduction to Python

In this tutorial, we will dive diretly into coding in versatile **python** language. Python can be used as **Calculator"


In [1]:
print(5/8)
print(5+8)
print(5-8)
print(5*8)

0.625
13
-3
40


In [2]:
# This is a comment line
# Exponentiation
print(4 ** 2)

# Modulo
print(18 % 7)



16
4


In [3]:
# How much is your $100 worth after 7 years? with compound interest rate of 10 %
print(100*1.1**7)

194.87171000000012


# Variables

- Names are Case-sensitive
- Types of primitive data types
    - int
    - float
    - string
    - boolean

In [4]:
# Creating a variable and assigned value: int
savings = 1000

In [5]:
# Create a variable factor: float
growth_multiplier = 1.10

# Calculate result
result = savings*growth_multiplier**7
print(result)

1948.7171000000012


In [6]:
# String and Boolean data types
# Create a variable desc: string
desc = "compound interest"

# Create a variable profitable: Boolean
profitable = True

In [7]:
# To check type of variables
print(type(savings))
print(type(growth_multiplier))
print(type(result))
print(type(desc))
print(type(profitable))



<class 'int'>
<class 'float'>
<class 'float'>
<class 'str'>
<class 'bool'>


In [8]:
# Several variables to experiment with
savings = 100
growth_multiplier = 1.1
desc = "compound interest"

# Assign product of factor and savings to year1
year1 = savings*growth_multiplier

# Print the type of year1
print(type(year1))

# Assign sum of desc and desc to doubledesc
doubledesc = desc + desc

# Print out doubledesc
print(doubledesc)

<class 'float'>
compound interestcompound interest


## Type conversion

In [9]:
# Definition of savings and result
savings = 100
result = 100 * 1.10 ** 7

# Fix the printout
print("I started with $" + str(savings) + " and now have $" + str(result) + ". Awesome!")

# Definition of pi_string
pi_string = "3.1415926"

# Convert pi_string into float: pi_float
pi_float = float(pi_string)

I started with $100 and now have $194.87171000000012. Awesome!


# Chapter 2: Lists

To store more than one data of different types, lists are used. Lists can also contain lists.

In [10]:
# Creating a list
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Create list areas
areas = [hall, kit, liv, bed, bath]

# Print areas
print(areas)


[11.25, 18.0, 20.0, 10.75, 9.5]


In [11]:
# Creating list with different data types
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Adapt list areas
areas = ["hallway", hall, "kitchen", kit, "living room", liv, "bedroom", bed, "bathroom", bath]

# Print areas
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


In [12]:
# List of Lists


# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# house information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom", bed],
         ["bathroom", bath]]

# Print out house
print(house)

# Print out the type of house
print(type(house))

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]
<class 'list'>


# Subsetting lists
# Lists index are zero-based. That's mean that the first element has index 0


In [13]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Print out second element from areas
print(areas[1])

# Print out last element from areas
print(areas[-1])

# Print out the area of the living room
print(areas[5])

11.25
9.5
20.0


In [14]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Sum of kitchen and bedroom area: eat_sleep_area
eat_sleep_area = areas[3] + areas[7]

# Print the variable eat_sleep_area
print(eat_sleep_area)

28.75


# Slicing and dicing

In [15]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to create downstairs
downstairs = areas[0:6]

# Use slicing to create upstairs
upstairs = areas[-4:]

# Print out downstairs and upstairs
print(downstairs)
print(upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


In [16]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Alternative slicing to create downstairs
downstairs = areas[:6]

# Alternative slicing to create upstairs
upstairs = areas[-4:]

In [17]:
house = [['hallway', 11.25],
 ['kitchen', 18.0],
 ['living room', 20.0],
 ['bedroom', 10.75],
 ['bathroom', 9.5]]

In [18]:
house[-1][1]

9.5

# List Manipulation
- Change list elements
- add list elements
- delete list elements

In [19]:
# Replace list elements
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Correct the bathroom area
areas[-1] = 10.50

# Change "living room" to "chill zone"
areas[4] = "chill zone"

In [20]:
areas

['hallway',
 11.25,
 'kitchen',
 18.0,
 'chill zone',
 20.0,
 'bedroom',
 10.75,
 'bathroom',
 10.5]

# Extend a list

In [21]:
# Create the areas list and make some changes
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0, 
         "bedroom", 10.75, "bathroom", 10.50]

# Add poolhouse data to areas, new list is areas_1
areas_1 = areas + ["poolhouse", 24.5]

# Add garage data to areas_1, new list is areas_2
areas_2 = areas_1 + ["garage", 15.45]

In [22]:
print(areas)
print(areas_1)
print(areas_2)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]


# Delete List Elements

In [23]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

In [24]:
del(areas[-4:-2])

In [25]:
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'garage', 15.45]


# Inner working of Lists

In [26]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Create areas_copy
areas_copy = areas[:]

# Change areas_copy
areas_copy[0] = 5.0

# Print areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


# Functions
- Functions are reusable code


In [27]:
areas = [11.25, 18.0, 20.0, 10.75, 9.50]
max(areas)

20.0

In [28]:
round(1.68,1)

1.7

In [29]:
round(1.68)

2

In [30]:
help(round)

Help on built-in function round in module builtins:

round(...)
    round(number[, ndigits]) -> number
    
    Round a number to a given precision in decimal digits (default 0 digits).
    This returns an int when called with one argument, otherwise the
    same type as the number. ndigits may be negative.



In [31]:
round(1.68,0)

2.0

# Familiar functions

In [32]:
# Create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True

# Print out type of var1
print(type(var1))

# Print out length of var1
print(len(var1))

# Convert var2 to an integer: out2
out2 = int(var2)

<class 'list'>
4


In [33]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [34]:
help(complex)

Help on class complex in module builtins:

class complex(object)
 |  complex(real[, imag]) -> complex number
 |  
 |  Create a complex number from a real part and an optional imaginary part.
 |  This is equivalent to (real + imag*1j) where imag defaults to 0.
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |  
 |  __format__(...)
 |      complex.__format__() -> str
 |      
 |      Convert to a string according to format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getnewargs__(...)
 |  
 |  __gt__(self, va

# Multiple arguements

In [35]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full = first + second

# Sort full in descending order: full_sorted
full_sorted = sorted(full, reverse = True)

# Print out full_sorted
print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


# Methods
Methods are functions that belong to objects only

In [36]:
sister = "liz"
sister.capitalize()

'Liz'

In [37]:
sister.replace('z','s')

'lis'

In [38]:
height = 1.73
# bit_length method is not available 
# height.bit_length()

In [39]:
height.conjugate()

1.73

In [40]:
height.is_integer()

False

In [41]:
height.hex()

'0x1.bae147ae147aep+0'

In [42]:
# Methods of list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]
print(areas.index("kitchen"))
print(areas.count(11.25))
print(areas.reverse())

2
1
None


In [43]:
print(areas)

[9.5, 'bathroom', 10.75, 'bedroom', 20.0, 'living room', 18.0, 'kitchen', 11.25, 'hallway']


## areas.reverse() does not return anything, rather it reverses the original list

## String Methods


In [44]:
# string to experiment with: place
place = "poolhouse"

# Use upper() on place: place_up
place_up = place.upper()

# Print out place and place_up
print(place)
print(place_up)

# Print out the number of o's in place
print(place.count("o"))

poolhouse
POOLHOUSE
3


Nice! Notice from the printouts that the <code>upper()</code> method does not change the object it is called on. This will be different for lists in the next exercise!

## Lists methods


In [45]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0
print(areas.index(20.0))

# Print out how often 14.5 appears in areas
print(areas.count(9.50))

2
1


In [46]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse and garage size
areas.append(24.5)
areas.append(15.45)

# Print out areas
print(areas)

# Reverse the orders of the elements in areas
areas.reverse()

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]


In [47]:
print(areas)

[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


# Chapter 3: Packages

Packages consists of many python scripts known as module
You have to install packages before you can use it

In [48]:
import numpy as np

In [49]:
# Definition of radius
r = 0.43

# Import the math package
import math

# Calculate C
C = 2*math.pi*r

# Calculate A
A = math.pi*r**2

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


In [50]:
# Selective import
# Definition of radius
r = 192500

# Import radians function of math package
from math import radians

# Travel distance of Moon if 12 degrees. Store in dist.
dist = r*radians(12)

# Print out dist
print(dist)

40317.10572106901


In [51]:
from scipy.linalg import inv as my_inv

In [52]:
my_inv([[1,2], [3,4]])

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# Chapter 4: Numpy

In [53]:
z = "tyuiop"
h = "g"
while h in z:
   print(h, end=" ")


In [54]:
print([i.lower() for i in "STUDENT"])


['s', 't', 'u', 'd', 'e', 'n', 't']


# List Recap
- Powerful
- Collection of values
- Hold different datatypes
- Change, add, remove (del)
- Need for data science
    - Mathetical operations on collections of data
    - Speed

In [56]:
height = [1.67, 1.80, 1.60]
weight = [76, 80, 70]
#weight/height**2

# To solve the above error, numpy (Numeric Python) is used
Numpy is
- Numeric Python
- Alternative to Python List: Numpy Array
- Calculations over entire array (element wise calculations)
- Easy and fast

In [57]:
import numpy as np

In [58]:
np_height = np.array(height)
np_weight = np.array(weight)
bmi = np_weight/np_height**2

In [59]:
bmi

array([27.25088745, 24.69135802, 27.34375   ])

In [60]:
# numpy array contains only single data type
np.array([1,"Liz",5.24])

array(['1', 'Liz', '5.24'], dtype='<U11')

In [61]:
python_list = [1,2,3]
numpy_array = np.array([1,2,3])
print(python_list + python_list)
print(numpy_array + numpy_array)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [62]:
# Numpy subsetting is very similar to List subsetting
bmi[0]


27.250887446663558

In [63]:
bmi[-1]

27.343749999999996

In [64]:
bmi[:2]

array([27.25088745, 24.69135802])

In [65]:
bmi > 25

array([ True, False,  True])

In [66]:
bmi[bmi>25]

array([27.25088745, 27.34375   ])

In [67]:
# Your First Numpy Array
# Create list baseball 
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a Numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


In [68]:
import pandas as pd
mlb = pd.read_csv("mlb.csv")

In [69]:
mlb.head()


Name   Team       Position    Height(inches)    Weight(pounds)   \
0    Adam_Donachie    BAL        Catcher                74             180.0   
1        Paul_Bako    BAL        Catcher                74             215.0   
2  Ramon_Hernandez    BAL        Catcher                72             210.0   
3     Kevin_Millar    BAL  First_Baseman                72             210.0   
4      Chris_Gomez    BAL  First_Baseman                73             188.0   

    Age   
0  22.99  
1  34.69  
2  30.78  
3  35.43  
4  35.71

In [70]:
list(mlb[mlb.columns[4]].isna()).index(True)

640

In [71]:
mlb.iloc[640,:]

Name                   Kirk_Saarloos
 Team                            CIN
 Position           Starting_Pitcher
 Height(inches)                   72
 Weight(pounds)                  NaN
 Age                           27.77
Name: 640, dtype: object

In [72]:
mlb.iloc[640,4]

nan

In [73]:
mlb.iloc[640,4] = 204

In [74]:
height_in = list(mlb[mlb.columns[3]])
weight_lb = list(mlb[mlb.columns[4]])

In [75]:
# Baseball player's height

# height is available as a regular list

# Import numpy
import numpy as np

# Create a Numpy array from height: np_height
np_height_in = np.array(height_in)

# Print out np_height
print(np_height_in)

# Convert np_height to m: np_height_m
np_height_m = 0.0254*np_height_in

# Print np_height_m
print(np_height_m)

[74 74 72 ... 75 75 73]
[1.8796 1.8796 1.8288 ... 1.905  1.905  1.8542]


In [76]:
# height and weight are available as a regular lists

# Import numpy
import numpy as np

# Create array from height with correct units: np_height_m
np_height_m = np.array(height_in) * 0.0254

# Create array from weight with correct units: np_weight_kg 
np_weight_kg = np.array(weight_lb) * 0.453592

# Calculate the BMI: bmi
bmi = np_weight_kg/np_height_m**2


In [77]:
bmi

array([23.11037639, 27.60406069, 28.48080465, ..., 25.62295933,
       23.74810865, 25.72686361])

# Light weight baseball players

In [78]:
# height and weight are available as a regular lists

# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height_in) * 0.0254
np_weight_kg = np.array(weight_lb) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light = bmi < 21

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])

[False False False ... False False False]
[20.54255679 20.54255679 20.69282047 20.69282047 20.34343189 20.34343189
 20.69282047 20.15883472 19.4984471  20.69282047 20.9205219 ]


In [79]:
np.isnan(bmi).sum().sum()

0

# subsetting numpy arrays

In [80]:
# height and weight are available as a regular lists

# Import numpy
import numpy as np

# Store weight and height lists as numpy arrays
np_weight_lb = np.array(weight_lb)
np_height_in = np.array(height_in)

# Print out the weight at index 50
print(np_weight_lb[50])

# Print out sub-array of np_height: index 100 up to and including index 110
print(np_height_in[100:111])

195.0
[73 72 74 73 74 72 73 69 72 73 75]


# Your first 2D Numpy Array

In [81]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D Numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


In [82]:
baseball_df = mlb[[mlb.columns[3],mlb.columns[4]]]

In [83]:
type(baseball_df)

pandas.core.frame.DataFrame

In [84]:
baseball = baseball_df.values.tolist()

In [85]:
type(baseball)

list

In [86]:
baseball

[[74.0, 180.0],
 [74.0, 215.0],
 [72.0, 210.0],
 [72.0, 210.0],
 [73.0, 188.0],
 [69.0, 176.0],
 [69.0, 209.0],
 [71.0, 200.0],
 [76.0, 231.0],
 [71.0, 180.0],
 [73.0, 188.0],
 [73.0, 180.0],
 [74.0, 185.0],
 [74.0, 160.0],
 [69.0, 180.0],
 [70.0, 185.0],
 [72.0, 197.0],
 [73.0, 189.0],
 [75.0, 185.0],
 [78.0, 219.0],
 [79.0, 230.0],
 [76.0, 205.0],
 [74.0, 230.0],
 [76.0, 195.0],
 [72.0, 180.0],
 [71.0, 192.0],
 [75.0, 225.0],
 [77.0, 203.0],
 [74.0, 195.0],
 [73.0, 182.0],
 [74.0, 188.0],
 [78.0, 200.0],
 [73.0, 180.0],
 [75.0, 200.0],
 [73.0, 200.0],
 [75.0, 245.0],
 [75.0, 240.0],
 [74.0, 215.0],
 [69.0, 185.0],
 [71.0, 175.0],
 [74.0, 199.0],
 [73.0, 200.0],
 [73.0, 215.0],
 [76.0, 200.0],
 [74.0, 205.0],
 [74.0, 206.0],
 [70.0, 186.0],
 [72.0, 188.0],
 [77.0, 220.0],
 [74.0, 210.0],
 [70.0, 195.0],
 [76.0, 244.0],
 [75.0, 195.0],
 [73.0, 200.0],
 [75.0, 200.0],
 [76.0, 212.0],
 [76.0, 224.0],
 [78.0, 210.0],
 [74.0, 205.0],
 [74.0, 220.0],
 [76.0, 195.0],
 [77.0, 200.0],
 [81.0, 

# baseball data in 2D form

In [87]:
# baseball is available as a regular list of lists

# Import numpy package
import numpy as np

# Create a 2D Numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the shape of np_baseball
print(np_baseball.shape)

(1034, 2)


# subsetting 2D Numpy array

In [88]:
# baseball is available as a regular list of lists

# Import numpy package
import numpy as np

# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 50th row of np_baseball
print(np_baseball[49,:])

# Select the entire second column of np_baseball: np_weight
np_weight_lb = np_baseball[:,1]

# Print out height of 124th player
print(np_baseball[123,0])

[ 74. 210.]
76.0


# 2D Arithmetic

In [89]:
baseball_df = mlb[[mlb.columns[3],mlb.columns[4],mlb.columns[5]]]
baseball = baseball_df.values.tolist()

In [90]:
# baseball is available as a regular list of lists
# update is available as 2D Numpy array

# Import numpy package
import numpy as np

# Create np_baseball (3 cols)
np_baseball = np.array(baseball)

# Print out addition of np_baseball and update
#print(np_baseball + updated)

# Create Numpy array: conversion
conversion = np.array([0.0254,0.453592,1])

# Print out product of np_baseball and conversion
print(np_baseball*conversion)

[[ 1.8796  81.64656 22.99   ]
 [ 1.8796  97.52228 34.69   ]
 [ 1.8288  95.25432 30.78   ]
 ...
 [ 1.905   92.98636 25.19   ]
 [ 1.905   86.18248 31.01   ]
 [ 1.8542  88.45044 27.92   ]]


# Data Analysis using statistics

In [91]:
np_baseball.shape

(1034, 3)

In [92]:
np.mean(np_baseball[:,0])

73.6972920696325

In [93]:
np.mean(np_baseball[:,1])

201.69148936170214

In [94]:
np.mean(np_baseball[:,2])

28.736711798839462

In [95]:
np.median(np_baseball[:,0])

74.0

In [96]:
np.median(np_baseball[:,1])

200.0

In [97]:
np.median(np_baseball[:,2])

27.925

In [98]:
np.corrcoef(np_baseball[:,0], np_baseball[:,1])

array([[1.        , 0.53166462],
       [0.53166462, 1.        ]])

In [99]:
np.std(np_baseball[:,1])

20.97130269805308

In [100]:
np.sort(np_baseball[:,1])

array([150., 150., 150., ..., 275., 278., 290.])

# To check the speed of numpy

## Generate data

In [101]:
height = np.round(np.random.normal(1.75,2.0,5000),2)
weight = np.round(np.random.normal(60.32,15,5000),2)

# Average vs median

In [102]:
# np_baseball is available

# Import numpy
import numpy as np

# Create np_height from np_baseball
np_height_in = np_baseball[:,0]

# Print out the mean of np_height
print(np.mean(np_height_in))

# Print out the median of np_height
print(np.median(np_height_in))

73.6972920696325
74.0


# Explore the baseball data

In [103]:
# np_baseball is available

# Import numpy
import numpy as np

# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0],np_baseball[:,1])
print("Correlation: " + str(corr))

Average: 73.6972920696325
Median: 74.0
Standard Deviation: 2.304703041620148
Correlation: [[1.         0.53166462]
 [0.53166462 1.        ]]


# Blend it all together

In [104]:
fifa = pd.read_csv("fifa.csv")
fifa.head()

id                     name   rating  position   height    foot   rare  \
0    1001             Gábor Király       69        GK      191   Right      0   
1  100143             Frederik Boi       65         M      184   Right      0   
2  100264          Tomasz Szewczuk       57         A      185   Right      0   
3  100325   Steeve Joseph-Reinette       63         D      180    Left      0   
4  100326             Kamel Chafni       72         M      181   Right      0   

   pace  shooting  passing  dribbling  defending  heading  diving  handling  \
0                                                              70        66   
1    61        65       63         59         62       62                     
2    65        54       43         53         55       74                     
3    68        38       51         46         64       71                     
4    75        64       67         72         57       66                     

   kicking  reflexes  speed   positioning  
0       63        74     35          66.0  
1                                     NaN  
2                                     NaN  
3                                     NaN  
4                                     NaN

In [105]:
heights = fifa[fifa.columns[4]].values.tolist()
positions = fifa[fifa.columns[3]].values.tolist()

In [106]:
# heights and positions are available as lists

# Import numpy
import numpy as np

# Convert positions and heights to numpy arrays: np_positions, np_heights
np_heights = np.array(heights)
np_positions = np.array(positions)

# Heights of the goalkeepers: gk_heights
gk_heights = np_heights[np_positions == ' GK']

# Heights of the other players: other_heights
other_heights = np_heights[np_positions != ' GK']

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

Median height of goalkeepers: 188.0
Median height of other players: 181.0
